name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Build, tag, and run, testing
      env:
        IMAGE_TAG: repoforsampletest
      run: |
        docker build -t $IMAGE_TAG .
        docker run -p 8794:80 $IMAGE_TAG
        OUTPUT=$(hostname -i)
        echo "${OUTPUT}"
        curl -v http://echo "${OUTPUT}":80/
        curl -v echo "${OUTPUT}":80/
      ###docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
